apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: sample-test-api # This must match the 'app' label on your pods
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on
      targetPort: 8080 # The port your pod's container is listening on