name: Publish Spring Boot Docker Image

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven # or 'gradle'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }} # Or use GITHUB_TOKEN for public repos
      
	  - name: Build and push Docker image
		uses: docker/build-push-action@v6
		with:
		  context: .
		  push: true
		  tags: ghcr.io/${{ github.repository }}:latest
		  platforms: linux/amd64,linux/arm64