name: Publish Spring Boot Docker Image

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
env:
  # GKE cluster configuration
  REGISTRY: ghcr.io
  GKE_CLUSTER: sample-test
  GKE_ZONE: asia-east1-a # e.g., us-central1-c
  
  # GHCR image details
  GHCR_IMAGE: ghcr.io/${{ github.repository }}
  GHCR_IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven # or 'gradle'

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }} # Or use GITHUB_TOKEN for public repos


      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.GHCR_IMAGE }}:${{ env.GHCR_IMAGE_TAG }}


      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}


      - name: Deploy to GKE
        run: |
         kubectl apply -f k8s/
         kubectl set image deployment/sample-test-api sample-container=${{ env.GHCR_IMAGE }}:${{ env.GHCR_IMAGE_TAG }}
         